name: Start application
description: Once done, the application is ready on `localhost:80`.

runs:
  using: composite
  steps:
    - name: Get frontend build
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist
    - name: Start containers
      run: |
        export COUCHDB_USER="refooduser"
        export COUCHDB_PASSWORD="refoodmdp"
        docker compose up --detach
      shell: bash
    - name: Wait for frontend
      uses: docker://benel/wait-for-response:1
      with:
        args: http://localhost/ 200 30000 500

    - name: Get samples
      uses: actions/download-artifact@v4
      with:
        name: samples
    
    - name: Upload samples
      run: |
        echo "Uploading sample_data.json to CouchDB..."
        curl -v -X POST http://localhost:5984/refood_db/_bulk_docs \
          -H "Content-Type: application/json" \
          -d @sample_data.json | head -50
        echo ""
        echo "Checking if data was loaded..."
        curl -s http://localhost:5984/refood_db/_all_docs?limit=5
      shell: bash

    - name: Wait for backend
      uses: docker://benel/wait-for-response:1
      with:
        args: http://localhost:5984/refood_db/_all_docs?limit=10 200 30000 500